# Generated by Django 2.2.7 on 2020-02-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rankinglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankinglist.Player')),
                ('rankinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='rankinglist.Rankinglist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playedat', models.DateField()),
                ('set1playerone', models.IntegerField(default=0)),
                ('set1playertwo', models.IntegerField(default=0)),
                ('set2playerone', models.IntegerField(default=0)),
                ('set2playertwo', models.IntegerField(default=0)),
                ('set3playerone', models.IntegerField(default=0)),
                ('set3playertwo', models.IntegerField(default=0)),
                ('playerone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerone', to='rankinglist.Player')),
                ('playertwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playertwo', to='rankinglist.Player')),
                ('rankinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankinglist.Rankinglist')),
            ],
        ),
    ]
