# Generated by Django 2.2.7 on 2020-02-29 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rankinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='leistungsklasse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
