# Generated by Django 2.2.7 on 2020-02-29 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankinglist', '0002_auto_20200229_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='playerone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='playertwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playertwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
