# Generated by Django 2.2.7 on 2020-03-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankinglist', '0003_auto_20200229_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankinglist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
