# Generated by Django 2.2.7 on 2020-03-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankinglist', '0004_rankinglist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('geplant', 'geplant'), ('gespielt', 'gespielt'), ('abgebrochen', 'abgebrochen')], default='geplant', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='playedat',
            field=models.DateTimeField(),
        ),
    ]
