# Generated by Django 2.2.7 on 2020-03-16 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankinglist', '0006_rankinglist_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankinglist',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
