# Generated by Django 2.2.7 on 2020-03-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankinglist', '0008_auto_20200316_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
    ]
