# Generated by Django 2.2.7 on 2020-04-21 12:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankinglist', '0008_auto_20200316_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='set1playerone',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)], verbose_name='Satz1 - Spieler 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='set1playertwo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)], verbose_name='Satz1 - Spieler 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='set2playerone',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)], verbose_name='Satz2 - Spieler 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='set2playertwo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)], verbose_name='Satz2 - Spieler 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='set3playerone',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Satz3 - Spieler 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='set3playertwo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Satz3 - Spieler 2'),
        ),
        migrations.AlterField(
            model_name='rankinglist',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('position', 'rankinglist', 'player'), name='uniqueranking'),
        ),
    ]
