# Generated by Django 2.2.7 on 2020-03-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankinglist', '0009_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Spieler', 'verbose_name_plural': 'Spieler'},
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rankinglist.Club'),
        ),
    ]
