# Generated by Django 2.2.7 on 2020-04-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankinglist', '0009_auto_20200421_1453'),
        ('rankinglist', '0010_auto_20200323_0715'),
    ]

    operations = [
    ]
