# Generated by Django 2.2.7 on 2020-04-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankinglist', '0012_auto_20200422_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
